version: '3.8'

services: 
  web: 
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=docker_django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docker_django


volumes: 
  postgres_data:
#To persist the data beyond the life of the container we configured a volume. 
#This config will bind postgres_data to the "/var/lib/postgresql/data/" 
#directory in the container.